CREATE OR REPLACE TRIGGER REG
INSTEAD OF insert
ON REGISTRO
FOR EACH ROW
 DECLARE
  ENTIDADID number; --ID DE LA ENTIDAD 
  ENTIDAD_N number; --CONTADOR DE ENTIDADES
  ACREDID number; --ID DE LA ENTIDAD 
  ACRED_N number; --CONTADOR DE ENTIDADES
  TIPOR_N number; --CONTADOR DE TIPO DE REGISTRO
  TIPORID number; -- ID TIPO DE REGISTRO
  TIPOM_N number; --CONTADOR DE TIPO DE MUESTRA
  TIPOMID number; -- ID TIPO DE MUESTRA
  ORDEN_N number; --CONTADOR DE ORDEN
  ORDENID number; -- ID ORDEN
  CLASE_N number; --CONTADOR DE CLASE
  CLASEID number; -- ID CLASE 
  EPIN_N number; --CONTADOR DE EPITETOINF
  EPINID number; -- ID EPITETOINF  
  PREP_N number; --CONTADOR DE EPITETOINF
  PREPID number; -- ID EPITETOINF 
  PAIS_N number; --CONTADOR DE PAIS
  PAISID number; -- ID PAIS
  DEP_N number; --CONTADOR DE DEPARTAMENTOS
  DEPID number; -- ID DEPARTAMENTOS
  MUN_N number; --CONTADOR DE DEPARTAMENTOS
  MUNID number; -- ID DEPARTAMENTOS  
  LOC_N number; --CONTADOR DE DEPARTAMENTOS
  LOCID number; -- ID DEPARTAMENTOS    
  EPITES_N number; --CONTADOR DE EPITETO ESPECIFICO
  EPITESID number; -- ID DE EPITETO ESPECIFICO
  FILO_N number; --CONTADOR DE FILOS
  FILOID number; -- ID DE FILOS
  GENERO_N number; --CONTADOR DE GENERO
  GENEROID number; -- ID DE GENERO
  CAT_N number; --CONTADOR DE CATEGORIA DE TAXON
  CATID number; -- ID DE CATEGORIA DE TAXON
  FAM_N number; --CONTADOR DE FAMILIA
  FAMID number; -- ID DE FAMILIA
BEGIN
  --ASIGNACION DE VARIABLES A CONTADORES
 SELECT COUNT(ENTIDAD_ID) INTO ENTIDAD_N FROM ENTIDAD WHERE NOMBREENTIDAD = :NEW.NOMBREENTIDAD;
 SELECT COUNT(ACREDITACION_ID) INTO ACRED_N FROM ACREDITACIONORIGEN WHERE ACREDITACION = :NEW.ACREDITACION;
 SELECT COUNT(TIPOREGISTRO_ID) INTO TIPOR_N FROM TIPOREGISTRO WHERE TIPOREG = :NEW.TIPOREG;
 SELECT COUNT(ORDEN_ID) INTO ORDEN_N FROM ORDEN WHERE ORD = :NEW.ORD;
 SELECT COUNT(CLASE_ID) INTO CLASE_N FROM CLASE WHERE CLAS = :NEW.CLAS;
 SELECT COUNT(EPITETOINF_ID) INTO EPIN_N FROM EPITETOINF WHERE EPITIF = :NEW.EPITIF;
 SELECT COUNT(PREPARACIONES_ID) INTO PREP_N FROM PREPARACIONES WHERE PREPARACION = :NEW.PREPARACION;
 SELECT COUNT(PAIS_ID) INTO PAIS_N FROM PAIS WHERE PAIS = :NEW.PAIS;
 SELECT COUNT(DEPTO_ID) INTO DEP_N FROM DEPTO WHERE DEP = :NEW.DEP;
 SELECT COUNT(MUNICIPIO_ID) INTO MUN_N FROM MUNICIPIO WHERE MUN = :NEW.MUN;
 SELECT COUNT(LOCALIDAD_ID) INTO LOC_N FROM LOCALIDAD WHERE LOC = :NEW.LOC;
 SELECT COUNT(EPITETOESPECIFICO_ID) INTO EPITES_N FROM EPITETOESPECIFICO WHERE EPITETO = :NEW.EPITETO; 
 SELECT COUNT(FILO_ID) INTO FILO_N FROM FILO WHERE FILO = :NEW.FILO; 
 SELECT COUNT(GENERO_ID) INTO GENERO_N FROM GENERO WHERE GEN = :NEW.GEN; 
 SELECT COUNT(CATEGORIA_ID) INTO CAT_N FROM CATTAXON WHERE TAXON = :NEW.TAXON; 
 
 --VERIFICADORES DE EXISTENCIA
IF (ENTIDAD_N=0)--ENTIDAD
  THEN
     INSERT INTO ENTIDAD (NOMBREENTIDAD, NIT) VALUES (:NEW.NOMBREENTIDAD,:NEW.NIT);
END IF;
IF (ACRED_N=0)--ACREDITACION
  THEN
     INSERT INTO ACREDITACIONORIGEN (ACREDITACION) VALUES (:NEW.ACREDITACION);
END IF;
IF (TIPOR_N=0)--VERIFICACION DEL TIPO DE REGISTRO
  THEN
     INSERT INTO TIPOREGISTRO (TIPOREG) VALUES (:NEW.TIPOREG);
END IF;
IF (TIPOM_N=0)--VERIFICACION DEL TIPO DE MUESTRA
  THEN
     INSERT INTO TIPOMUESTRA (TIPOMUES) VALUES (:NEW.TIPOMUES);
END IF;     
IF (TIPOM_N=0)--VERIFICACION DEL TIPO DE MUESTRA
  THEN
     INSERT INTO TIPOMUESTRA (TIPOMUES) VALUES (:NEW.TIPOMUES);
END IF;     
IF (ORDEN_N=0)--VERIFICACION DEL ORDEN
  THEN
     INSERT INTO ORDEN (ORD) VALUES (:NEW.ORD);
END IF;
IF (CLASE_N=0)--VERIFICACION DEL CLASE
  THEN
     INSERT INTO CLASE (CLAS) VALUES (:NEW.CLAS);
END IF;  
IF (EPIN_N=0)--VERIFICACION DEL EPITETO INFRAESPECIFICO
  THEN
     INSERT INTO EPITETOINF (EPITIF) VALUES (:NEW.EPITIF);
END IF;
IF (PREP_N=0)--VERIFICACION DE PREPARACION
  THEN
     INSERT INTO PREPARACIONES (PREPARACION) VALUES (:NEW.PREPARACION);
END IF;
IF (PAIS_N=0)--VERIFICACION DE PAIS
  THEN
     INSERT INTO PAIS (PAIS) VALUES (:NEW.PAIS);

SELECT PAIS_ID INTO PAISID FROM PAIS WHERE PAIS = :NEW.PAIS; --ANTES DE INGRESAR UN POSIBLE NUEVO DEPARTAMENTO SE HA DE CONOCER EL ID DEL PAIS
END IF;
IF (DEP_N=0)--VERIFICACION DE DEPARTAMENTO
  THEN
     INSERT INTO DEPTO (PAIS_ID, DEP) VALUES (PAISID, :NEW.DEP); 

SELECT DEPTO_ID INTO DEPID FROM DEPTO WHERE DEP = :NEW.DEP; --ANTES DE INGRESAR UN POSIBLE NUEVO MUNICIPIO, SE HA DE CONOCER EL ID DEL DEPARTAMENTO
END IF;
IF (MUN_N=0)--VERIFICACION DE MUNICIPIO
  THEN
     INSERT INTO MUNICIPIO (DEPTO_ID, MUN) VALUES (DEPID, :NEW.MUN);

SELECT MUNICIPIO_ID INTO MUNID FROM MUNICIPIO WHERE MUN = :NEW.MUN; --ANTES DE INGRESAR UN POSIBLE NUEVO MUNICIPIO, SE HA DE CONOCER EL ID DEL DEPARTAMENTO
END IF;
IF (LOC_N=0)--VERIFICACION DE LOCALIDAD
  THEN
     INSERT INTO LOCALIDAD (MUNICIPIO_ID, LOC) VALUES (MUNID, :NEW.LOC);
END IF;    
IF (EPITES_N=0)--VERIFICACION DE EPITETO ESPECIFICO
  THEN
     INSERT INTO EPITETOESPECIFICO (EPITETO) VALUES (:NEW.EPITETO);
END IF;     
IF (FILO_N=0)--VERIFICACION DE FILO
  THEN
     INSERT INTO FILO (FIL) VALUES (:NEW.FIL);
END IF;
IF (GENERO_N=0)--VERIFICACION DE GENERO
  THEN
     INSERT INTO GENERO (GEN) VALUES (:NEW.GEN);
END IF;    
IF (CAT_N=0)--VERIFICACION DE CATEGORIA DE TAXON
  THEN
     INSERT INTO CATTAXON (TAXON) VALUES (:NEW.TAXON);
END IF;     
IF (FAM_N=0)--VERIFICACION DE CATEGORIA DE TAXON
  THEN
     INSERT INTO FAMILIA (FAM) VALUES (:NEW.FAM);     
END IF;
--RECUPERACION DE CLAVES AJENAS
SELECT ENTIDAD_ID INTO ENTIDADID FROM ENTIDAD WHERE NOMBREENTIDAD= :NEW.NOMBREENTIDAD;
SELECT ACREDITACION_ID INTO ACREDID FROM ACREDITACIONORIGEN WHERE ACREDITACION= :NEW.ACREDITACION;
SELECT TIPOREGISTRO_ID INTO TIPORID FROM TIPOREGISTRO WHERE TIPOREG= :NEW.TIPOREG;
SELECT TIPOMUESTRA_ID INTO TIPOMID FROM TIPOMUESTRA WHERE TIPOMUES= :NEW.TIPOMUES;
SELECT ORDEN_ID INTO ORDENID FROM ORDEN WHERE ORD = :NEW.ORD;
SELECT CLASE_ID INTO CLASEID FROM CLASE WHERE CLAS = :NEW.CLAS;
SELECT EPITETOINF_ID INTO EPINID FROM EPITETOINF WHERE EPITIF = :NEW.EPITIF;
SELECT PREPARACIONES_ID INTO PREPID FROM PREPARACIONES WHERE PREPARACION = :NEW.PREPARACION;
SELECT PAIS_ID INTO PAISID FROM PAIS WHERE PAIS = :NEW.PAIS;
SELECT LOCALIDAD_ID INTO LOCID FROM LOCALIDAD WHERE LOC = :NEW.LOC;
SELECT EPITETOESPECIFICO_ID INTO EPITESID FROM EPITETOESPECIFICO WHERE EPITETO = :NEW.EPITETO; 
SELECT FILO_ID INTO FILOID FROM FILO WHERE FILO = :NEW.FILO; 
SELECT GENERO_ID INTO GENEROID FROM GENERO WHERE GEN = :NEW.GEN; 
SELECT CATEGORIA_ID INTO CATID FROM CATTAXON WHERE TAXON = :NEW.TAXON; 
SELECT FAMILIA_ID INTO FAMID FROM FAMILIA WHERE FAM = :NEW.FAM; 
--INSERSION EN LA TABLA ESPECIMEN
INSERT INTO ESPECIMEN (ENTIDAD_ID, ACREDITACIONORIGEN_ID, TIPOREGISTRO_ID, TIPOMUESTRA_ID, PREPARACIONES_ID, MUNICIPIO_ID, LOCALIDAD_ID, ORDEN_ID, CLASE_ID, FAMILIA_ID, FILO_ID, GENERO_ID, EPITETOESPECIFICO_ID, CATTAXON_ID, EPITETOINF_ID, NUMEROCATALOGO, FECHAEVENTO, COLECCION, NUMERORNC, IDREGBIOLOG, COLECTOR, NUMCOLECTOR, IDENTIFICADOPOR, COMENTARIOSREG, LATITUDDECIMAL, LONGITUDDECIMAL, DATUMGEODESICO, ELEVMINIMA, ELEVMAX, PROFMIN, PROFMAX, COMENTARIOSUBICACION, INFORETENIDA, COMENTARIOSIDENT, califIdentificacion, REINO, NOMBRECOMUN, numInds, nombreCientifico) VALUES(ENTIDADID,ACREDID,TIPORID, TIPOMID, PREPID, MUNID,  LOCID, ORDENID, CLASEID, FAMID, FILOID,GENEROID, EPITESID, CATID, EPINID, :NEW.NUMEROCATALOGO, :NEW.FECHAEVENTO, :NEW.COLECCION, :NEW.NUMERORNC, :NEW.IDREGBIOLOG, :NEW.COLECTOR, :NEW.NUMCOLECTOR, :NEW.IDENTIFICADOPOR, :NEW.COMENTARIOSREG, :NEW.LATITUDDECIMAL, :NEW.LONGITUDDECIMAL, :NEW.DATUMGEODESICO, :NEW.ELEVMINIMA, :NEW.ELEVMAX, :NEW.PROFMIN, :NEW.PROFMAX, :NEW.COMENTARIOSUBICACION, :NEW.INFORETENIDA, :NEW.COMENTARIOSIDENT, :NEW.califIdentificacion, :NEW.REINO, :NEW.NOMBRECOMUN, :NEW.numInds, :NEW.nombreCientifico); 
END;





INSERT INTO REGISTRO (NOMBREENTIDAD, NIT, ACREDITACION, TIPOREG, TIPOMUES, IdRegBiolog, numeroRnc, NumeroCatalogo, preparacion,colector, numColector, identificadoPoR, comentariosReg, FechaEvento, PAIS, dep, mun, LOC, latitudDecimal, LOngintuddecimaL, datumGeodesico, elevMinima, elevMax, profMin, profMax, ComentariosUbicacion, infoRetenida, nombreCientifico, TaxOn, numInds, califIdentificacion, comentariosIdent, Reino, Fil, Clas, Ord, FAM, GEN, EpIteto, epitif, nombreComun)
                VALUES('Universidad del Qundío', '890.000.432-8', 'Resolución 00386, junio 20 de 2000. CRQ', 'SD','SD','MAUQ.M1.CA 03',94,'M1.CA 03','Montaje en alfiler','Gómez W. Marin. O',0,'Gómez W. Marin. O','SD','27/05/2005','Colombia','Quindío','Armenia','Hojas anchas',0,0, 'SD','1500',0,0,0, 'SD','SD','Choeradodis  SD','Familia',1,'SD','SD','Animal','arthropoda','Insecta','Mantodea','Vatidae','Choeradodis','SD','SD','SD');
                

